import type { NextPage } from 'next'
import Head from 'next/head'

import { PostCard } from '../components';

import { getPosts } from '../services';
import { IPost } from '../utils/interfaces';

type Props = {
  posts:IPost[]
}

const Home: NextPage<Props> = ({posts}) => {
  return (  
    <div>
      <Head>
        <title>CMS Bolg</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {posts.map((post:IPost) => <PostCard key={post.node.id} post={post}/>)}
    </div>
  )
}

export async function getStaticProps() {
  const posts:IPost[] = (await getPosts()) || []
    return {
    props:{posts}
  }
}

export default Home
